{
 "title": "Rails",
 "description": "Rails dashboard for prometheus_exporter on ec2 instance",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(ruby_http_requests_total,app)"
   },
   {
    "name": "environment",
    "query": "label_values(ruby_http_requests_total{app=~\"$app\"},environment)"
   },
   { "name": "controller", "query": "api/.*" },
   { "name": "sidekiq" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Web Workers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ruby_rss{type=~'master|web|puma_master|puma_worker',app=~\"$app\",environment=~\"$environment\"}) "
    }
   ]
  },
  {
   "title": "Sidekiq Workers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ruby_rss{type='sidekiq',app=~\"$app\",environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "Requests / s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller=~\"$controller\"}[5m]))"
    }
   ]
  },
  {
   "title": "Sidekiqs / s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(ruby_sidekiq_job_duration_seconds{app=~\"$app\",environment=~\"$environment\"}[60m]))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Request Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(ruby_http_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) / rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) * 1000) > 0",
     "legendFormat": "max"
    },
    {
     "expr": "quantile(0.95, rate(ruby_http_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) / rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) * 1000) > 0",
     "legendFormat": "95th"
    },
    {
     "expr": "quantile(0.99, rate(ruby_http_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) / rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) * 1000) > 0",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Request Count / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m])) > 0"
    }
   ]
  },
  {
   "title": "Web workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ruby_rss{type=~'master|web|puma_master|puma_worker',app=~\"$app\",environment=~\"$environment\"}) "
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Duration (all actions)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(ruby_http_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) / rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) * 1000 > 0",
       "legendFormat": "{{controller}}/{{action}}"
      }
     ]
    },
    {
     "title": "Request Count / s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[5m]) > 0",
       "legendFormat": "{{controller}}/{{action}}"
      }
     ]
    },
    {
     "title": "Max Request Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(rate(ruby_http_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\"}[5m]) / rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller=~\"$controller\"}[5m]) > 0)",
       "legendFormat": "Max Request",
       "target": "carbon.*"
      },
      {
       "expr": "max(rate(ruby_http_sql_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\"}[5m]) / rate(ruby_http_sql_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller=~\"$controller\"}[5m]) > 0)",
       "legendFormat": "Max SQL"
      }
     ]
    },
    {
     "title": "Successful Requests / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ruby_http_requests_total{app=~\"$app\",environment=~\"$environment\",status=~\"^[23].*\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\"}[5m])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Avg Request Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(ruby_http_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\"}[5m]) / rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller=~\"$controller\"}[5m]) > 0)",
       "legendFormat": "Avg Request"
      },
      {
       "expr": "avg(rate(ruby_http_sql_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\"}[5m]) / rate(ruby_http_sql_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller!=\"status\",controller=~\"$controller\"}[5m]) > 0)",
       "legendFormat": "Avg SQL"
      }
     ]
    },
    {
     "title": "Errors / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ruby_http_requests_total{app=~\"$app\",environment=~\"$environment\",status=~\"^[45].*\",controller=~\"$controller\"}[5m])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Slow Actions",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "topk(10,avg(rate(ruby_http_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[1w]) / rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[1w])) by (controller, action)) \n"
      }
     ]
    },
    {
     "title": "Slow SQL Actions",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "topk(10,avg(rate(ruby_http_sql_duration_seconds_sum{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[1w]) / rate(ruby_http_sql_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[1w])) by (controller, action)) \n"
      }
     ]
    },
    {
     "title": "Most Frequent Actions / Day",
     "type": "table-old",
     "description": "Average number of requests per day during last week",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "topk(10,sum(rate(ruby_http_duration_seconds_count{app=~\"$app\",environment=~\"$environment\",controller=~\"$controller\"}[1w]) * 3600 * 24) by (controller, action))"
      }
     ]
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(ruby_cache_hit{app=\"$app\", environment=\"$environment\"}[30s])",
     "legendFormat": "Hit"
    },
    {
     "expr": "increase(ruby_cache_miss{app=\"$app\", environment=\"$environment\"}[30s])",
     "legendFormat": "Miss"
    },
    {
     "expr": "increase(ruby_cache_hit{app=\"$app\", environment=\"$environment\"}[30s]) / (increase(ruby_cache_hit{app=\"$app\", environment=\"$environment\"}[30s]) + increase(ruby_cache_miss{app=\"$app\", environment=\"$environment\"}[30s])) * 100",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Clears",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ruby_cache_clear{app=\"$app\", environment=\"$environment\"}[30s]) > 0",
     "legendFormat": "Clears"
    }
   ]
  },
  {
   "title": "Sidekiqs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(ruby_sidekiq_job_duration_seconds{app=~\"$app\",environment=~\"$environment\",job_name=~\"$sidekiq\"}[5m]) / rate(ruby_sidekiq_jobs_total{app=~\"$app\",environment=~\"$environment\",job_name=~\"$sidekiq\"}[5m]) > 0",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job Count / s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ruby_sidekiq_jobs_total{app=~\"$app\",environment=~\"$environment\",job_name=~\"$sidekiq\"}[5m]) > 0",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Slow Jobs",
     "type": "table-old",
     "description": "Average duration of last week",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "topk(10,avg(rate(ruby_sidekiq_job_duration_seconds{app=~\"$app\",environment=~\"$environment\"}[1w]) / rate(ruby_sidekiq_jobs_total{app=~\"$app\",environment=~\"$environment\"}[1w])) by (job_name))"
      }
     ]
    },
    {
     "title": "Most Frequent Jobs / Day",
     "type": "table-old",
     "description": "Number of runs per day during last week",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "topk(10,sum(rate(ruby_sidekiq_jobs_total{app=~\"$app\",environment=~\"$environment\"}[1w]) * 3600 * 24) by (job_name))"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (ruby_rss{app=~\"$app\",environment=~\"$environment\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Object Allocation Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(ruby_allocated_objects_total{app=~\"$app\",environment=~\"$environment\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Heap Web",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(ruby_heap_free_slots{app=~\"$app\",environment=~\"$environment\",type=~\"master|web|puma_master|puma_worker\"})",
       "legendFormat": "Min Free Slots {{type}}"
      },
      {
       "expr": "max(ruby_heap_live_slots{app=~\"$app\",environment=~\"$environment\",type=~\"master|web|puma_master|puma_worker\"})",
       "legendFormat": "Max Live Slots {{type}}"
      }
     ]
    },
    {
     "title": "Heap Sidekiq",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(ruby_heap_free_slots{app=~\"$app\",environment=~\"$environment\",type=\"sidekiq\"}) without (pid)",
       "legendFormat": "Min Free Slots {{type}}"
      },
      {
       "expr": "max(ruby_heap_live_slots{app=~\"$app\",environment=~\"$environment\",type=\"sidekiq\"}) without (pid)",
       "legendFormat": "Max Live Slots {{type}}"
      }
     ]
    }
   ]
  }
 ]
}